version: "3"

services:
  nodejs:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - /dev/shm:/dev/shm
    # command: tail -f /dev/null   # Add this line
